making some changes to the buildspec file

diff --git a/config/buildspec.yml b/config/buildspec.yml
--- a/config/buildspec.yml
+++ b/config/buildspec.yml
@@ -25,20 +25,15 @@ phases:
       # Cloning Client repo
       - env
       - echo `pwd`
-#      - |
-#        if [ "${TEST_SUITE_EXH}" != "none" ] || [ "${TEST_SUITE_FMS}" != "none" ] || [ "${TEST_SUITE_CXH}" != "none" ] || [ "${TEST_SUITE_ECOMM}" != "none" ] || [ "${TEST_SUITE_AGRON}" != "none" ]; then
-#          npm install
-#          npm run e2e-setup
-#          ls
-#          chown -R cps:cps ./ && chmod -R 755 ./
-#        fi
-#  # The POST BUILD phase - Wrapped all suite executions in a retry statment
+      - bundle install
+
+  # The POST BUILD phase - Wrapped all suite executions in a retry statment
   post_build:
     commands:
-#      - AWS_RUN=true
-#      - ERRORS_TO_CONSOLE=false
-#      - ERROR=0
-#      - env
+      - AWS_RUN=true
+      - ERRORS_TO_CONSOLE=false
+      - ERROR=0
+      - env
 #      - |
 #        if [ "${TEST_SUITE_EXH}" != "none" ]; then
 #          CONFIG="./tests-exh/wdio.conf.js"
@@ -48,31 +43,6 @@ phases:
 #          COMMAND="node_modules/.bin/wdio $CONFIG $SUITE $BROWSER $ENV"
 #          eval $COMMAND || ERROR=1
 #        fi
-#      - |
-#        if [ "${TEST_SUITE_CXH}" != "none" ]; then
-#          CONFIG="./tests-cxh/wdio.conf.js"
-#          SUITE="--suite $TEST_SUITE_CXH"
-#          BROWSER="--browser=headless"
-#          ENV="--env=$ENV_STAGE"
-#          EMAIL="--email=$EMAIL_USERNAME --email_password=$EMAIL_PASSWORD"
-#          EMPLOYEE="--e_username=$EMPLOYEE_USERNAME --e_password=$EMPLOYEE_PASSWORD"
-#          COMMAND="node_modules/.bin/wdio $CONFIG $SUITE $BROWSER $ENV $EMAIL $EMPLOYEE"
-#          eval $COMMAND || ERROR=1
-#        fi
-#      - |
-#        if [ "${TEST_SUITE_ECOMM}" != "none" ]; then
-#          COMMAND="node_modules/.bin/wdio ./tests-ecomm/wdio.conf.js --suite $TEST_SUITE_ECOMM --browser=headless --env=$ENV_STAGE"
-#          eval $COMMAND || ERROR=1
-#        fi
-#      - |
-#        if [ "${TEST_SUITE_AGRON}" != "none" ]; then
-#          COMMAND="node_modules/.bin/wdio ./tests-agronomy/wdio.conf.js --suite $TEST_SUITE_AGRON --browser=headless --env=$ENV_STAGE"
-#          eval $COMMAND || ERROR=1
-#        fi
-#      - |
-#        if [ "${TEST_SUITE_EXH}" != "none" ] || [ "${TEST_SUITE_FMS}" != "none" ] || [ "${TEST_SUITE_CXH}" != "none" ] || [ "${TEST_SUITE_ECOMM}" != "none" ] || [ "${TEST_SUITE_AGRON}" != "none" ]; then
-#          cat logs/new-relic-run-report.json | curl -d @- -X POST -H "Content-Type&#58 application/json" -H "X-Insert-Key:$NEW_RELIC_INSIGHTS_INSERT_KEY" https://insights-collector.newrelic.com/v1/accounts/1971382/events
-#        fi
 #      - echo ERROR STATE AT THE END IS... $ERROR
 #      - echo evaluating $CODEBUILD_INITIATOR for return status
 #      - echo $CODEBUILD_INITIATOR
@@ -81,4 +51,5 @@ phases:
 #            echo "Setting ERROR to 0"
 #            ERROR=0
 #        fi
-#      - exit $ERROR
+      - echo `ERROR`
+      - exit $ERROR
